import { Industry } from "@/types";

export const industries: Array<Industry> = [
  "Administrative Services - Archiving Service",
  "Administrative Services - Call Center",
  "Administrative Services - Collection Agency",
  "Administrative Services - College Recruiting",
  "Administrative Services - Courier Service",
  "Administrative Services - Debt Collections",
  "Administrative Services - Delivery",
  "Administrative Services - Document Preparation",
  "Administrative Services - Employee Benefits",
  "Administrative Services - Extermination Service",
  "Administrative Services - Facilities Support Services",
  "Administrative Services - Housekeeping Service",
  "Administrative Services - Human Resources",
  "Administrative Services - Knowledge Management",
  "Administrative Services - Office Administration",
  "Administrative Services - Packaging Services",
  "Administrative Services - Physical Security",
  "Administrative Services - Project Management",
  "Administrative Services - Staffing Agency",
  "Administrative Services - Trade Shows",
  "Administrative Services - Virtual Workforce",
  "Advertising - Ad Exchange",
  "Advertising - Ad Network",
  "Advertising - Ad Retargeting",
  "Advertising - Ad Server",
  "Advertising - Ad Targeting",
  "Advertising - Advertising",
  "Advertising - Advertising Platforms",
  "Advertising - Affiliate Marketing",
  "Advertising - Local Advertising",
  "Advertising - Mobile Advertising",
  "Advertising - Outdoor Advertising",
  "Advertising - SEM",
  "Advertising - Social Media Advertising",
  "Advertising - Video Advertising",
  "Agriculture and Farming - Agriculture",
  "Agriculture and Farming - AgTech",
  "Agriculture and Farming - Animal Feed",
  "Agriculture and Farming - Aquaculture",
  "Agriculture and Farming - Equestrian",
  "Agriculture and Farming - Farming",
  "Agriculture and Farming - Forestry",
  "Agriculture and Farming - Horticulture",
  "Agriculture and Farming - Hydroponics",
  "Agriculture and Farming - Livestock",
  "Apps - App Discovery",
  "Apps - Apps",
  "Apps - Consumer Applications",
  "Apps - Enterprise Applications",
  "Apps - Mobile Apps",
  "Apps - Reading Apps",
  "Apps - Web Apps",
  "Artificial Intelligence - Artificial Intelligence",
  "Artificial Intelligence - Intelligent Systems",
  "Artificial Intelligence - Machine Learning",
  "Artificial Intelligence - Natural Language Processing",
  "Artificial Intelligence - Predictive Analytics",
  "Biotechnology - Bioinformatics",
  "Biotechnology - Biometrics",
  "Biotechnology - Biopharma",
  "Biotechnology - Biotechnology",
  "Biotechnology - Genetics",
  "Biotechnology - Life Science",
  "Biotechnology - Neuroscience",
  "Biotechnology - Quantified Self",
  "Clothing and Apparel - Fashion",
  "Clothing and Apparel - Laundry and Dry-cleaning",
  "Clothing and Apparel - Lingerie",
  "Clothing and Apparel - Shoes",
  "Commerce and Shopping - Auctions",
  "Commerce and Shopping - Classifieds",
  "Commerce and Shopping - Collectibles",
  "Commerce and Shopping - Consumer Reviews",
  "Commerce and Shopping - Coupons",
  "Commerce and Shopping - E-Commerce",
  "Commerce and Shopping - E-Commerce Platforms",
  "Commerce and Shopping - Flash Sale",
  "Commerce and Shopping - Gift",
  "Commerce and Shopping - Gift Card",
  "Commerce and Shopping - Gift Exchange",
  "Commerce and Shopping - Gift Registry",
  "Commerce and Shopping - Group Buying",
  "Commerce and Shopping - Local Shopping",
  "Commerce and Shopping - Made to Order",
  "Commerce and Shopping - Marketplace",
  "Commerce and Shopping - Online Auctions",
  "Commerce and Shopping - Personalization",
  "Commerce and Shopping - Point of Sale",
  "Commerce and Shopping - Price Comparison",
  "Commerce and Shopping - Rental",
  "Commerce and Shopping - Retail",
  "Commerce and Shopping - Retail Technology",
  "Commerce and Shopping - Shopping",
  "Commerce and Shopping - Shopping Mall",
  "Commerce and Shopping - Social Shopping",
  "Commerce and Shopping - Sporting Goods",
  "Commerce and Shopping - Vending and Concessions",
  "Commerce and Shopping - Virtual Goods",
  "Commerce and Shopping - Wholesale",
  "Community and Lifestyle - Adult",
  "Community and Lifestyle - Baby",
  "Community and Lifestyle - Cannabis",
  "Community and Lifestyle - Children",
  "Community and Lifestyle - Communities",
  "Community and Lifestyle - Dating",
  "Community and Lifestyle - Elderly",
  "Community and Lifestyle - Family",
  "Community and Lifestyle - Funerals",
  "Community and Lifestyle - Humanitarian",
  "Community and Lifestyle - Leisure",
  "Community and Lifestyle - LGBT",
  "Community and Lifestyle - Lifestyle",
  "Community and Lifestyle - Mens",
  "Community and Lifestyle - Online Forums",
  "Community and Lifestyle - Parenting",
  "Community and Lifestyle - Pet",
  "Community and Lifestyle - Private Social Networking",
  "Community and Lifestyle - Professional Networking",
  "Community and Lifestyle - Q&A",
  "Community and Lifestyle - Religion",
  "Community and Lifestyle - Retirement",
  "Community and Lifestyle - Sex Industry",
  "Community and Lifestyle - Sex Tech",
  "Community and Lifestyle - Social",
  "Community and Lifestyle - Social Entrepreneurship",
  "Community and Lifestyle - Teenagers",
  "Community and Lifestyle - Virtual World",
  "Community and Lifestyle - Wedding",
  "Community and Lifestyle - Womens",
  "Community and Lifestyle - Young Adults",
  "Consumer Electronics  - Computer",
  "Consumer Electronics - Consumer Electronics",
  "Consumer Electronics - Drones",
  "Consumer Electronics - Electronics",
  "Consumer Electronics - Google Glass",
  "Consumer Electronics - Mobile Devices",
  "Consumer Electronics - Nintendo",
  "Consumer Electronics - Playstation",
  "Consumer Electronics - Roku",
  "Consumer Electronics - Smart Home",
  "Consumer Electronics - Wearables",
  "Consumer Electronics - Windows Phone",
  "Consumer Electronics - Xbox",
  "Consumer Goods - Beauty",
  "Consumer Goods - Comics",
  "Consumer Goods - Consumer Goods",
  "Consumer Goods - Cosmetics",
  "Consumer Goods - DIY",
  "Consumer Goods - Drones",
  "Consumer Goods - Eyewear",
  "Consumer Goods - Fast-Moving Consumer Goods",
  "Consumer Goods - Flowers",
  "Consumer Goods - Furniture",
  "Consumer Goods - Green Consumer Goods",
  "Consumer Goods - Handmade",
  "Consumer Goods - Jewelry",
  "Consumer Goods - Lingerie",
  "Consumer Goods - Shoes",
  "Consumer Goods - Tobacco",
  "Consumer Goods - Toys",
  "Content and Publishing - Blogging Platforms",
  "Content and Publishing - Content Delivery Network",
  "Content and Publishing - Content Discovery",
  "Content and Publishing - Content Syndication",
  "Content and Publishing - Creative Agency",
  "Content and Publishing - DRM",
  "Content and Publishing - EBooks",
  "Content and Publishing - Journalism",
  "Content and Publishing - News",
  "Content and Publishing - Photo Editing",
  "Content and Publishing - Photo Sharing",
  "Content and Publishing - Photography",
  "Content and Publishing - Printing",
  "Content and Publishing - Publishing",
  "Content and Publishing - Social Bookmarking",
  "Content and Publishing - Video Editing",
  "Content and Publishing - Video Streaming",
  "Data and Analytics - A/B Testing",
  "Data and Analytics - Analytics",
  "Data and Analytics - Application Performance Management",
  "Data and Analytics - Artificial Intelligence",
  "Data and Analytics - Big Data",
  "Data and Analytics - Bioinformatics",
  "Data and Analytics - Biometrics",
  "Data and Analytics - Business Intelligence",
  "Data and Analytics - Consumer Research",
  "Data and Analytics - Data Integration",
  "Data and Analytics - Data Mining",
  "Data and Analytics - Data Visualization",
  "Data and Analytics - Database",
  "Data and Analytics - Facial Recognition",
  "Data and Analytics - Geospatial",
  "Data and Analytics - Image Recognition",
  "Data and Analytics - Intelligent Systems",
  "Data and Analytics - Location Based Services",
  "Data and Analytics - Machine Learning",
  "Data and Analytics - Market Research",
  "Data and Analytics - Natural Language Processing",
  "Data and Analytics - Predictive Analytics",
  "Data and Analytics - Product Research",
  "Data and Analytics - Quantified Self",
  "Data and Analytics - Speech Recognition",
  "Data and Analytics - Test and Measurement",
  "Data and Analytics - Text Analytics",
  "Data and Analytics - Usability Testing",
  "Design - CAD",
  "Design - Consumer Research",
  "Design - Data Visualization",
  "Design - Fashion",
  "Design - Graphic Design",
  "Design - Human Computer Interaction",
  "Design - Industrial Design",
  "Design - Interior Design",
  "Design - Market Research",
  "Design - Mechanical Design",
  "Design - Product Design",
  "Design - Product Research",
  "Design - Usability Testing",
  "Design - UX Design",
  "Design - Web Design",
  "Education - Alumni",
  "Education - Charter Schools",
  "Education - College Recruiting",
  "Education - Continuing Education",
  "Education - Corporate Training",
  "Education - E-Learning",
  "Education - EdTech",
  "Education - Education",
  "Education - Edutainment",
  "Education - Higher Education",
  "Education - Language Learning",
  "Education - MOOC",
  "Education - Music Education",
  "Education - Personal Development",
  "Education - Primary Education",
  "Education - Secondary Education",
  "Education - Skill Assessment",
  "Education - STEM Education",
  "Education - Textbook",
  "Education - Training",
  "Education - Tutoring",
  "Education - Vocational Education",
  "Energy - Battery",
  "Energy - Biofuel",
  "Energy - Biomass Energy",
  "Energy - Clean Energy",
  "Energy - Electrical Distribution",
  "Energy - Energy",
  "Energy - Energy Efficiency",
  "Energy - Energy Management",
  "Energy - Energy Storage",
  "Energy - Fossil Fuels",
  "Energy - Fuel",
  "Energy - Fuel Cell",
  "Energy - Oil and Gas",
  "Energy - Power Grid",
  "Energy - Renewable Energy",
  "Energy - Solar",
  "Energy - Wind Energy",
  "Events - Concerts",
  "Events - Event Management",
  "Events - Event Promotion",
  "Events - Events",
  "Events - Nightclubs",
  "Events - Nightlife",
  "Events - Reservations",
  "Events - Ticketing",
  "Events - Wedding",
  "Financial Services - Accounting",
  "Financial Services - Angel Investment",
  "Financial Services - Asset Management",
  "Financial Services - Auto Insurance",
  "Financial Services - Banking",
  "Financial Services - Bitcoin",
  "Financial Services - Commercial Insurance",
  "Financial Services - Commercial Lending",
  "Financial Services - Consumer Lending",
  "Financial Services - Credit",
  "Financial Services - Credit Bureau",
  "Financial Services - Credit Cards",
  "Financial Services - Crowdfunding",
  "Financial Services - Cryptocurrency",
  "Financial Services - Debit Cards",
  "Financial Services - Debt Collections",
  "Financial Services - Finance",
  "Financial Services - Financial Exchanges",
  "Financial Services - Financial Services",
  "Financial Services - FinTech",
  "Financial Services - Fraud Detection",
  "Financial Services - Funding Platform",
  "Financial Services - Gift Card",
  "Financial Services - Health Insurance",
  "Financial Services - Hedge Funds",
  "Financial Services - Impact Investing",
  "Financial Services - Incubators",
  "Financial Services - Insurance",
  "Financial Services - InsurTech",
  "Financial Services - Leasing",
  "Financial Services - Lending",
  "Financial Services - Life Insurance",
  "Financial Services - Micro Lending",
  "Financial Services - Mobile Payments",
  "Financial Services - Payments",
  "Financial Services - Personal Finance",
  "Financial Services - Prediction Markets",
  "Financial Services - Property Insurance",
  "Financial Services - Real Estate Investment",
  "Financial Services - Stock Exchanges",
  "Financial Services - Trading Platform",
  "Financial Services - Transaction Processing",
  "Financial Services - Venture Capital",
  "Financial Services - Virtual Currency",
  "Financial Services - Wealth Management",
  "Food and Beverage - Bakery",
  "Food and Beverage - Brewing",
  "Food and Beverage - Cannabis",
  "Food and Beverage - Catering",
  "Food and Beverage - Coffee",
  "Food and Beverage - Confectionery",
  "Food and Beverage - Cooking",
  "Food and Beverage - Craft Beer",
  "Food and Beverage - Dietary Supplements",
  "Food and Beverage - Distillery",
  "Food and Beverage - Farmers Market",
  "Food and Beverage - Food and Beverage",
  "Food and Beverage - Food Delivery",
  "Food and Beverage - Food Processing",
  "Food and Beverage - Food Trucks",
  "Food and Beverage - Fruit",
  "Food and Beverage - Grocery",
  "Food and Beverage - Nutrition",
  "Food and Beverage - Organic Food",
  "Food and Beverage - Recipes",
  "Food and Beverage - Restaurants",
  "Food and Beverage - Seafood",
  "Food and Beverage - Snack Food",
  "Food and Beverage - Tea",
  "Food and Beverage - Tobacco",
  "Food and Beverage - Wine And Spirits",
  "Food and Beverage - Winery",
  "Gaming - Casual Games",
  "Gaming - Console Games",
  "Gaming - Contests",
  "Gaming - Fantasy Sports",
  "Gaming - Gambling",
  "Gaming - Gamification",
  "Gaming - Gaming",
  "Gaming - MMO Games",
  "Gaming - Online Games",
  "Gaming - PC Games",
  "Gaming - Serious Games",
  "Gaming - Video Games",
  "Government and Military - CivicTech",
  "Government and Military - Government",
  "Government and Military - GovTech",
  "Government and Military - Law Enforcement",
  "Government and Military - Military",
  "Government and Military - National Security",
  "Government and Military - Politics",
  "Government and Military - Public Safety",
  "Government and Military - Social Assistance",
  "Hardware - 3D Technology",
  "Hardware - Application Specific Integrated Circuit (ASIC)",
  "Hardware - Augmented Reality",
  "Hardware - Cloud Infrastructure",
  "Hardware - Communication Hardware",
  "Hardware - Communications Infrastructure",
  "Hardware - Computer",
  "Hardware - Computer Vision",
  "Hardware - Consumer Electronics",
  "Hardware - Data Center",
  "Hardware - Data Center Automation",
  "Hardware - Data Storage",
  "Hardware - Drone Management",
  "Hardware - Drones",
  "Hardware - DSP",
  "Hardware - Electronic Design Automation (EDA)",
  "Hardware - Electronics",
  "Hardware - Embedded Systems",
  "Hardware - Field-Programmable Gate Array (FPGA)",
  "Hardware - Flash Storage",
  "Hardware - Google Glass",
  "Hardware - GPS",
  "Hardware - GPU",
  "Hardware - Hardware",
  "Hardware - Industrial Design",
  "Hardware - Laser",
  "Hardware - Lighting",
  "Hardware - Mechanical Design",
  "Hardware - Mobile Devices",
  "Hardware - Network Hardware",
  "Hardware - NFC",
  "Hardware - Nintendo",
  "Hardware - Optical Communication",
  "Hardware - Playstation",
  "Hardware - Private Cloud",
  "Hardware - Retail Technology",
  "Hardware - RFID",
  "Hardware - RISC",
  "Hardware - Robotics",
  "Hardware - Roku",
  "Hardware - Satellite Communication",
  "Hardware - Semiconductor",
  "Hardware - Sensor",
  "Hardware - Sex Tech",
  "Hardware - Telecommunications",
  "Hardware - Video Conferencing",
  "Hardware - Virtual Reality",
  "Hardware - Virtualization",
  "Hardware - Wearables",
  "Hardware - Windows Phone",
  "Hardware - Wireless",
  "Hardware - Xbox",
  "Health Care - Alternative Medicine",
  "Health Care - Assisted Living",
  "Health Care - Assistive Technology",
  "Health Care - Biopharma",
  "Health Care - Cannabis",
  "Health Care - Child Care",
  "Health Care - Clinical Trials",
  "Health Care - Cosmetic Surgery",
  "Health Care - Dental",
  "Health Care - Diabetes",
  "Health Care - Dietary Supplements",
  "Health Care - Elder Care",
  "Health Care - Electronic Health Record (EHR)",
  "Health Care - Emergency Medicine",
  "Health Care - Employee Benefits",
  "Health Care - Fertility",
  "Health Care - First Aid",
  "Health Care - Funerals",
  "Health Care - Genetics",
  "Health Care - Health Care",
  "Health Care - Health Diagnostics",
  "Health Care - Home Health Care",
  "Health Care - Hospital",
  "Health Care - Medical",
  "Health Care - Medical Device",
  "Health Care - Health",
  "Health Care - Nursing and Residential Care",
  "Health Care - Nutraceutical",
  "Health Care - Nutrition",
  "Health Care - Outpatient Care",
  "Health Care - Personal Health",
  "Health Care - Pharmaceutical",
  "Health Care - Psychology",
  "Health Care - Rehabilitation",
  "Health Care - Therapeutics",
  "Health Care - Veterinary",
  "Health Care - Wellness",
  "Information Technology - Business Information Systems",
  "Information Technology - CivicTech",
  "Information Technology - Cloud Data Services",
  "Information Technology - Cloud Management",
  "Information Technology - Cloud Security",
  "Information Technology - CMS",
  "Information Technology - Contact Management",
  "Information Technology - CRM",
  "Information Technology - Cyber Security",
  "Information Technology - Data Center",
  "Information Technology - Data Center Automation",
  "Information Technology - Data Integration",
  "Information Technology - Data Mining",
  "Information Technology - Data Visualization",
  "Information Technology - Document Management",
  "Information Technology - E-Signature",
  "Information Technology - Email",
  "Information Technology - GovTech",
  "Information Technology - Identity Management",
  "Information Technology - Information and Communications Technology (ICT)",
  "Information Technology - Information Services",
  "Information Technology - Information Technology",
  "Information Technology - Intrusion Detection",
  "Information Technology - IT Infrastructure",
  "Information Technology - IT Management",
  "Information Technology - Management Information Systems",
  "Information Technology - Messaging",
  "Information Technology - Military",
  "Information Technology - Network Security",
  "Information Technology - Penetration Testing",
  "Information Technology - Private Cloud",
  "Information Technology - Reputation",
  "Information Technology - Sales Automation",
  "Information Technology - Scheduling",
  "Information Technology - Social CRM",
  "Information Technology - Spam Filtering",
  "Information Technology - Technical Support",
  "Information Technology - Unified Communications",
  "Information Technology - Video Chat",
  "Information Technology - Video Conferencing",
  "Information Technology - Virtualization",
  "Information Technology - VoIP",
  "Internet Services - Cloud Computing",
  "Internet Services - Cloud Data Services",
  "Internet Services - Cloud Infrastructure",
  "Internet Services - Cloud Management",
  "Internet Services - Cloud Storage",
  "Internet Services - Darknet",
  "Internet Services - Domain Registrar",
  "Internet Services - E-Commerce Platforms",
  "Internet Services - Ediscovery",
  "Internet Services - Email",
  "Internet Services - Internet",
  "Internet Services - Internet of Things",
  "Internet Services - ISP",
  "Internet Services - Location Based Services",
  "Internet Services - Messaging",
  "Internet Services - Music Streaming",
  "Internet Services - Online Forums",
  "Internet Services - Online Portals",
  "Internet Services - Private Cloud",
  "Internet Services - Product Search",
  "Internet Services - Search Engine",
  "Internet Services - SEM",
  "Internet Services - Semantic Search",
  "Internet Services - Semantic Web",
  "Internet Services - SEO",
  "Internet Services - SMS",
  "Internet Services - Social Media",
  "Internet Services - Social Media Management",
  "Internet Services - Social Network",
  "Internet Services - Unified Communications",
  "Internet Services - Vertical Search",
  "Internet Services - Video Chat",
  "Internet Services - Video Conferencing",
  "Internet Services - Visual Search",
  "Internet Services - VoIP",
  "Internet Services - Web Browsers",
  "Internet Services - Web Hosting",
  "Lending and Investments - Angel Investment",
  "Lending and Investments - Banking",
  "Lending and Investments - Commercial Lending",
  "Lending and Investments - Consumer Lending",
  "Lending and Investments - Credit",
  "Lending and Investments - Credit Cards",
  "Lending and Investments - Financial Exchanges",
  "Lending and Investments - Funding Platform",
  "Lending and Investments - Hedge Funds",
  "Lending and Investments - Impact Investing",
  "Lending and Investments - Incubators",
  "Lending and Investments - Micro Lending",
  "Lending and Investments - Stock Exchanges",
  "Lending and Investments - Trading Platform",
  "Lending and Investments - Venture Capital",
  "Manufacturing - 3D Printing",
  "Manufacturing - Advanced Materials",
  "Manufacturing - Foundries",
  "Manufacturing - Industrial",
  "Manufacturing - Industrial Automation",
  "Manufacturing - Industrial Engineering",
  "Manufacturing - Industrial Manufacturing",
  "Manufacturing - Machinery Manufacturing",
  "Manufacturing - Manufacturing",
  "Manufacturing - Paper Manufacturing",
  "Manufacturing - Plastics and Rubber Manufacturing",
  "Manufacturing - Textiles",
  "Manufacturing - Wood Processing",
  "Media and Entertainment - Advice",
  "Media and Entertainment - Animation",
  "Media and Entertainment - Art",
  "Media and Entertainment - Audio",
  "Media and Entertainment - Audiobooks",
  "Media and Entertainment - Blogging Platforms",
  "Media and Entertainment - Broadcasting",
  "Media and Entertainment - Celebrity",
  "Media and Entertainment - Concerts",
  "Media and Entertainment - Content",
  "Media and Entertainment - Content Creators",
  "Media and Entertainment - Content Discovery",
  "Media and Entertainment - Content Syndication",
  "Media and Entertainment - Creative Agency",
  "Media and Entertainment - Digital Entertainment",
  "Media and Entertainment - Digital Media",
  "Media and Entertainment - DRM",
  "Media and Entertainment - EBooks",
  "Media and Entertainment - Edutainment",
  "Media and Entertainment - Event Management",
  "Media and Entertainment - Event Promotion",
  "Media and Entertainment - Events",
  "Media and Entertainment - Film",
  "Media and Entertainment - Film Distribution",
  "Media and Entertainment - Film Production",
  "Media and Entertainment - Guides",
  "Media and Entertainment - In-Flight Entertainment",
  "Media and Entertainment - Independent Music",
  "Media and Entertainment - Internet Radio",
  "Media and Entertainment - Journalism",
  "Media and Entertainment - Media and Entertainment",
  "Media and Entertainment - Motion Capture",
  "Media and Entertainment - Music",
  "Media and Entertainment - Music Education",
  "Media and Entertainment - Music Label",
  "Media and Entertainment - Music Streaming",
  "Media and Entertainment - Music Venues",
  "Media and Entertainment - Musical Instruments",
  "Media and Entertainment - News",
  "Media and Entertainment - Nightclubs",
  "Media and Entertainment - Nightlife",
  "Media and Entertainment - Performing Arts",
  "Media and Entertainment - Photo Editing",
  "Media and Entertainment - Photo Sharing",
  "Media and Entertainment - Photography",
  "Media and Entertainment - Podcast",
  "Media and Entertainment - Printing",
  "Media and Entertainment - Publishing",
  "Media and Entertainment - Reservations",
  "Media and Entertainment - Social Media",
  "Media and Entertainment - Social News",
  "Media and Entertainment - Theatre",
  "Media and Entertainment - Ticketing",
  "Media and Entertainment - TV",
  "Media and Entertainment - TV Production",
  "Media and Entertainment - Video",
  "Media and Entertainment - Video Editing",
  "Media and Entertainment - Video on Demand",
  "Media and Entertainment - Video Streaming",
  "Media and Entertainment - Virtual World",
  "Messaging and Telecommunications - Email",
  "Messaging and Telecommunications - Meeting Software",
  "Messaging and Telecommunications - Messaging",
  "Messaging and Telecommunications - SMS",
  "Messaging and Telecommunications - Unified Communications",
  "Messaging and Telecommunications - Video Chat",
  "Messaging and Telecommunications - Video Conferencing",
  "Messaging and Telecommunications - VoIP",
  "Messaging and Telecommunications - Wired Telecommunications",
  "Mobile - Android",
  "Mobile - Google Glass",
  "Mobile - IOS",
  "Mobile - MHealth",
  "Mobile - Mobile",
  "Mobile - Mobile Apps",
  "Mobile - Mobile Devices",
  "Mobile - Mobile Payments",
  "Mobile - Windows Phone",
  "Mobile - Wireless",
  "Music and Audio - Audio",
  "Music and Audio - Audiobooks",
  "Music and Audio - Independent Music",
  "Music and Audio - Internet Radio",
  "Music and Audio - Music",
  "Music and Audio - Music Education",
  "Music and Audio - Music Label",
  "Music and Audio - Music Streaming",
  "Music and Audio - Musical Instruments",
  "Music and Audio - Podcast",
  "Natural Resources - Biomass Energy",
  "Natural Resources - Fossil Fuels",
  "Natural Resources - Mineral",
  "Natural Resources - Mining",
  "Natural Resources - Mining Technology",
  "Natural Resources - Natural Resources",
  "Natural Resources - Oil and Gas",
  "Natural Resources - Precious Metals",
  "Natural Resources - Solar",
  "Natural Resources - Timber",
  "Natural Resources - Water",
  "Natural Resources - Wind Energy",
  "Navigation and Mapping - Geospatial",
  "Navigation and Mapping - GPS",
  "Navigation and Mapping - Indoor Positioning",
  "Navigation and Mapping - Location Based Services",
  "Navigation and Mapping - Mapping Services",
  "Navigation and Mapping - Navigation",
  "Other - Alumni",
  "Other - Association",
  "Other - B2B",
  "Other - B2C",
  "Other - Blockchain",
  "Other - Charity",
  "Other - Collaboration",
  "Other - Collaborative Consumption",
  "Other - Commercial",
  "Other - Consumer",
  "Other - Crowdsourcing",
  "Other - Customer Service",
  "Other - Desktop Apps",
  "Other - Emerging Markets",
  "Other - Enterprise",
  "Other - Ethereum",
  "Other - Franchise",
  "Other - Freemium",
  "Other - Generation Y",
  "Other - Generation Z",
  "Other - Homeless Shelter",
  "Other - Infrastructure",
  "Other - Knowledge Management",
  "Other - LGBT",
  "Other - Millennials",
  "Other - Non Profit",
  "Other - Peer to Peer",
  "Other - Professional Services",
  "Other - Project Management",
  "Other - Real Time",
  "Other - Retirement",
  "Other - Service Industry",
  "Other - Sharing Economy",
  "Other - Small and Medium Businesses",
  "Other - Social Bookmarking",
  "Other - Social Impact",
  "Other - Subscription Service",
  "Other - Technical Support",
  "Other - Underserved Children",
  "Other - Universities",
  "Payments - Billing",
  "Payments - Bitcoin",
  "Payments - Credit Cards",
  "Payments - Cryptocurrency",
  "Payments - Debit Cards",
  "Payments - Fraud Detection",
  "Payments - Mobile Payments",
  "Payments - Payments",
  "Payments - Transaction Processing",
  "Payments - Virtual Currency",
  "Platforms - Android",
  "Platforms - Facebook",
  "Platforms - Google",
  "Platforms - Google Glass",
  "Platforms - IOS",
  "Platforms - Linux",
  "Platforms - MacOS",
  "Platforms - Nintendo",
  "Platforms - Operating Systems",
  "Platforms - Playstation",
  "Platforms - Roku",
  "Platforms - Tizen",
  "Platforms - Twitter",
  "Platforms - WebOS",
  "Platforms - Windows",
  "Platforms - Windows Phone",
  "Platforms - Xbox",
  "Privacy and Security - Cloud Security",
  "Privacy and Security - Corrections Facilities",
  "Privacy and Security - Cyber Security",
  "Privacy and Security - DRM",
  "Privacy and Security - E-Signature",
  "Privacy and Security - Fraud Detection",
  "Privacy and Security - Homeland Security",
  "Privacy and Security - Identity Management",
  "Privacy and Security - Intrusion Detection",
  "Privacy and Security - Law Enforcement",
  "Privacy and Security - Network Security",
  "Privacy and Security - Penetration Testing",
  "Privacy and Security - Physical Security",
  "Privacy and Security - Privacy",
  "Privacy and Security - Security",
  "Professional Services - Accounting",
  "Professional Services - Business Development",
  "Professional Services - Career Planning",
  "Professional Services - Compliance",
  "Professional Services - Consulting",
  "Professional Services - Customer Service",
  "Professional Services - Employment",
  "Professional Services - Environmental Consulting",
  "Professional Services - Field Support",
  "Professional Services - Freelance",
  "Professional Services - Intellectual Property",
  "Professional Services - Innovation Management",
  "Professional Services - Legal",
  "Professional Services - Legal Tech",
  "Professional Services - Management Consulting",
  "Professional Services - Outsourcing",
  "Professional Services - Professional Networking",
  "Professional Services - Quality Assurance",
  "Professional Services - Recruiting",
  "Professional Services - Risk Management",
  "Professional Services - Social Recruiting",
  "Professional Services - Translation Service",
  "Real Estate - Architecture",
  "Real Estate - Building Maintenance",
  "Real Estate - Building Material",
  "Real Estate - Commercial Real Estate",
  "Real Estate - Construction",
  "Real Estate - Coworking",
  "Real Estate - Facility Management",
  "Real Estate - Fast-Moving Consumer Goods",
  "Real Estate - Green Building",
  "Real Estate - Home and Garden",
  "Real Estate - Home Decor",
  "Real Estate - Home Improvement",
  "Real Estate - Home Renovation",
  "Real Estate - Home Services",
  "Real Estate - Interior Design",
  "Real Estate - Janitorial Service",
  "Real Estate - Landscaping",
  "Real Estate - Property Development",
  "Real Estate - Property Management",
  "Real Estate - Real Estate",
  "Real Estate - Real Estate Investment",
  "Real Estate - Rental Property",
  "Real Estate - Residential",
  "Real Estate - Self-Storage",
  "Real Estate - Smart Building",
  "Real Estate - Smart Cities",
  "Real Estate - Smart Home",
  "Real Estate - Timeshare",
  "Real Estate - Vacation Rental",
  "Sales and Marketing - Advertising",
  "Sales and Marketing - Affiliate Marketing",
  "Sales and Marketing - App Discovery",
  "Sales and Marketing - App Marketing",
  "Sales and Marketing - Brand Marketing",
  "Sales and Marketing - Cause Marketing",
  "Sales and Marketing - Content Marketing",
  "Sales and Marketing - CRM",
  "Sales and Marketing - Digital Marketing",
  "Sales and Marketing - Digital Signage",
  "Sales and Marketing - Direct Marketing",
  "Sales and Marketing - Direct Sales",
  "Sales and Marketing - Email Marketing",
  "Sales and Marketing - Lead Generation",
  "Sales and Marketing - Lead Management",
  "Sales and Marketing - Local",
  "Sales and Marketing - Local Advertising",
  "Sales and Marketing - Local Business",
  "Sales and Marketing - Loyalty Programs",
  "Sales and Marketing - Marketing",
  "Sales and Marketing - Marketing Automation",
  "Sales and Marketing - Mobile Advertising",
  "Sales and Marketing - Multi-level Marketing",
  "Sales and Marketing - Outdoor Advertising",
  "Sales and Marketing - Personal Branding",
  "Sales and Marketing - Public Relations",
  "Sales and Marketing - Sales",
  "Sales and Marketing - Sales Automation",
  "Sales and Marketing - SEM",
  "Sales and Marketing - SEO",
  "Sales and Marketing - Social CRM",
  "Sales and Marketing - Social Media Advertising",
  "Sales and Marketing - Social Media Management",
  "Sales and Marketing - Social Media Marketing",
  "Sales and Marketing - Sponsorship",
  "Sales and Marketing - Video Advertising",
  "Science and Engineering - Advanced Materials",
  "Science and Engineering - Aerospace",
  "Science and Engineering - Artificial Intelligence",
  "Science and Engineering - Bioinformatics",
  "Science and Engineering - Biometrics",
  "Science and Engineering - Biopharma",
  "Science and Engineering - Biotechnology",
  "Science and Engineering - Chemical",
  "Science and Engineering - Chemical Engineering",
  "Science and Engineering - Civil Engineering",
  "Science and Engineering - Embedded Systems",
  "Science and Engineering - Environmental Engineering",
  "Science and Engineering - Human Computer Interaction",
  "Science and Engineering - Industrial Automation",
  "Science and Engineering - Industrial Engineering",
  "Science and Engineering - Intelligent Systems",
  "Science and Engineering - Laser",
  "Science and Engineering - Life Science",
  "Science and Engineering - Marine Technology",
  "Science and Engineering - Mechanical Engineering",
  "Science and Engineering - Nanotechnology",
  "Science and Engineering - Neuroscience",
  "Science and Engineering - Nuclear",
  "Science and Engineering - Quantum Computing",
  "Science and Engineering - Robotics",
  "Science and Engineering - Semiconductor",
  "Science and Engineering - Software Engineering",
  "Science and Engineering - STEM Education",
  "Software - 3D Technology",
  "Software - Android",
  "Software - App Discovery",
  "Software - Application Performance Management",
  "Software - Apps",
  "Software - Artificial Intelligence",
  "Software - Augmented Reality",
  "Software - Billing",
  "Software - Bitcoin",
  "Software - Browser Extensions",
  "Software - CAD",
  "Software - Cloud Computing",
  "Software - Cloud Management",
  "Software - CMS",
  "Software - Computer Vision",
  "Software - Consumer Applications",
  "Software - Consumer Software",
  "Software - Contact Management",
  "Software - CRM",
  "Software - Cryptocurrency",
  "Software - Data Center Automation",
  "Software - Data Integration",
  "Software - Data Storage",
  "Software - Data Visualization",
  "Software - Database",
  "Software - Developer APIs",
  "Software - Developer Platform",
  "Software - Developer Tools",
  "Software - Document Management",
  "Software - Drone Management",
  "Software - E-Learning",
  "Software - EdTech",
  "Software - Electronic Design Automation (EDA)",
  "Software - Embedded Software",
  "Software - Embedded Systems",
  "Software - Enterprise Applications",
  "Software - Enterprise Resource Planning (ERP)",
  "Software - Enterprise Software",
  "Software - Facial Recognition",
  "Software - File Sharing",
  "Software - IaaS",
  "Software - Image Recognition",
  "Software - IOS",
  "Software - Linux",
  "Software - Machine Learning",
  "Software - MacOS",
  "Software - Marketing Automation",
  "Software - Meeting Software",
  "Software - Mobile Apps",
  "Software - Mobile Payments",
  "Software - MOOC",
  "Software - Natural Language Processing",
  "Software - Open Source",
  "Software - Operating Systems",
  "Software - PaaS",
  "Software - Predictive Analytics",
  "Software - Presentation Software",
  "Software - Presentations",
  "Software - Private Cloud",
  "Software - Productivity Tools",
  "Software - QR Codes",
  "Software - Reading Apps",
  "Software - Retail Technology",
  "Software - Robotics",
  "Software - SaaS",
  "Software - Sales Automation",
  "Software - Scheduling",
  "Software - Sex Tech",
  "Software - Simulation",
  "Software - SNS",
  "Software - Social CRM",
  "Software - Software",
  "Software - Software Engineering",
  "Software - Speech Recognition",
  "Software - Task Management",
  "Software - Text Analytics",
  "Software - Transaction Processing",
  "Software - Video Conferencing",
  "Software - Virtual Assistant",
  "Software - Virtual Currency",
  "Software - Virtual Desktop",
  "Software - Virtual Goods",
  "Software - Virtual Reality",
  "Software - Virtual World",
  "Software - Virtualization",
  "Software - Web Apps",
  "Software - Web Browsers",
  "Software - Web Development",
  "Sports - American Football",
  "Sports - Baseball",
  "Sports - Basketball",
  "Sports - Boating",
  "Sports - Cricket",
  "Sports - Cycling",
  "Sports - Diving",
  "Sports - E-Sports",
  "Sports - Fantasy Sports",
  "Sports - Fitness",
  "Sports - Golf",
  "Sports - Hockey",
  "Sports - Hunting",
  "Sports - Outdoors",
  "Sports - Racing",
  "Sports - Recreation",
  "Sports - Rugby",
  "Sports - Sailing",
  "Sports - Skiing",
  "Sports - Soccer",
  "Sports - Sporting Goods",
  "Sports - Sports",
  "Sports - Surfing",
  "Sports - Swimming",
  "Sports - Table Tennis",
  "Sports - Tennis",
  "Sports - Ultimate Frisbee",
  "Sports - Volley Ball",
  "Sustainability - Biofuel",
  "Sustainability - Biomass Energy",
  "Sustainability - Clean Energy",
  "Sustainability - CleanTech",
  "Sustainability - Energy Efficiency",
  "Sustainability - Environmental Engineering",
  "Sustainability - Green Building",
  "Sustainability - Green Consumer Goods",
  "Sustainability - GreenTech",
  "Sustainability - Natural Resources",
  "Sustainability - Organic",
  "Sustainability - Pollution Control",
  "Sustainability - Recycling",
  "Sustainability - Renewable Energy",
  "Sustainability - Solar",
  "Sustainability - Sustainability",
  "Sustainability - Waste Management",
  "Sustainability - Water Purification",
  "Sustainability - Wind Energy",
  "Transportation - Air Transportation",
  "Transportation - Automotive",
  "Transportation - Autonomous Vehicles",
  "Transportation - Car Sharing",
  "Transportation - Courier Service",
  "Transportation - Delivery Service",
  "Transportation - Electric Vehicle",
  "Transportation - Ferry Service",
  "Transportation - Fleet Management",
  "Transportation - Food Delivery",
  "Transportation - Freight Service",
  "Transportation - Last Mile Transportation",
  "Transportation - Limousine Service",
  "Transportation - Logistics",
  "Transportation - Marine Transportation",
  "Transportation - Parking",
  "Transportation - Ports and Harbors",
  "Transportation - Procurement",
  "Transportation - Public Transportation",
  "Transportation - Railroad",
  "Transportation - Recreational Vehicles",
  "Transportation - Ride Sharing",
  "Transportation - Same Day Delivery",
  "Transportation - Shipping",
  "Transportation - Shipping Broker",
  "Transportation - Space Travel",
  "Transportation - Supply Chain Management",
  "Transportation - Taxi Service",
  "Transportation - Transportation",
  "Transportation - Warehousing",
  "Transportation - Water Transportation",
  "Travel and Tourism - Adventure Travel",
  "Travel and Tourism - Amusement Park and Arcade",
  "Travel and Tourism - Business Travel",
  "Travel and Tourism - Casino",
  "Travel and Tourism - Hospitality",
  "Travel and Tourism - Hotel",
  "Travel and Tourism - Museums and Historical Sites",
  "Travel and Tourism - Parks",
  "Travel and Tourism - Resorts",
  "Travel and Tourism - Timeshare",
  "Travel and Tourism - Tour Operator",
  "Travel and Tourism - Tourism",
  "Travel and Tourism - Travel",
  "Travel and Tourism - Travel Accommodations",
  "Travel and Tourism - Travel Agency",
  "Travel and Tourism - Vacation Rental",
  "Video - Animation",
  "Video - Broadcasting",
  "Video - Film",
  "Video - Film Distribution",
  "Video - Film Production",
  "Video - Motion Capture",
  "Video - TV",
  "Video - TV Production",
  "Video - Video",
  "Video - Video Editing",
  "Video - Video on Demand",
  "Video - Video Streaming",
];

export const INDUSTRY_OPTIONS = industries.map((industry) => ({
  label: industry,
  value: industry,
}));
